name: mix_widgets
description: "Additional widgets for Flutter Mix"
version: 0.0.1
homepage: https://fluttermix.com

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  mix: ^1.5.2
  flutter:
    sdk: flutter
  easy_debounce: ^2.0.3
  mix_annotations: ^0.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mix_generator: ^0.3.1
