name: mix_widgets
description: "Additional widgets for Flutter Mix"
version: 0.0.1
homepage: https://fluttermix.com

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  mix: ^1.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
